apiVersion: v1
kind: Namespace
metadata:
  name: suprachat
---
apiVersion: v1
kind: Service
metadata:
  name: suprachat-backend
  namespace: suprachat
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
    - name: web
      port: 80
      targetPort: web
  selector:
    app: suprachat-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: suprachat-backend
  namespace: suprachat
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: suprachat-backend
  template:
    metadata:
      labels:
        app: suprachat-backend
    spec:
      containers:
        - name: suprachat-backend
          image: ttl.sh/suprachat-backend-8372b766-ba42-4836-ada6-51764f21330c:2h@sha256:f9396ab72c099aa0acd33ef0a5e5ac9e504d1abb64ac1cce90adc96c9b786179
          ports:
            - name: web
              containerPort: 3001
          envFrom:
            - configMapRef:
                name: sc-backend-env
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-backend
                  key: SECRET_KEY
            - name: WEBIRC_PASS
              valueFrom:
                secretKeyRef:
                  name: sc-backend
                  key: WEBIRC_PASS
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: suprachat-backend
  namespace: suprachat
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
      - beta-api.suprachat.net
      secretName: sc-backend-cert
  rules:
    - host: beta-api.suprachat.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: suprachat-backend
                port:
                  name: web
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: suprachat
spec:
  acme:
    email: ivan.97galarz@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - http01:
          ingress:
            class: traefik
