default:
  image: node:18-slim
  before_script:
    - corepack enable
    - pnpm config set store-dir .pnpm-store

stages:
  - build
  - test
  - deploy

type-check:
  stage: build
  script:
    - pnpm install --frozen-lockfile
    - pnpm type-check
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

unit-test:
  stage: test
  script:
    - pnpm install
    - pnpm test

lint:
  stage: test
  script:
    - pnpm install
    - pnpm lint && pnpm format

deploy:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
