default:
  image: node:18-slim
  before_script:
    - corepack enable
    - pnpm config set store-dir .pnpm-store

stages:
  - build
  - test
  - deploy

type-check:
  stage: build
  script:
    - pnpm install --frozen-lockfile
    - pnpm type-check
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

lint:
  stage: build
  script:
    - pnpm install --frozen-lockfile
    - pnpm style-check
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

unit-test:
  stage: test
  script:
    - apt update && apt install -y curl
    - pnpm install --frozen-lockfile
    - SECRET_KEY=$SECRET_KEY pnpm test
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config get-contexts
  before_script: []
  # environment: production
  # script:
  #   - echo "Deploying application..."
  #   - echo "Application successfully deployed."
