default:
  image: node:18-slim
  before_script:
    - corepack enable
    - pnpm config set store-dir .pnpm-store

stages:
  - build
  - test
  - deploy

type-check:
  stage: build
  script:
    - pnpm install --frozen-lockfile
    - pnpm type-check
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

lint:
  stage: build
  script:
    - pnpm install
    - pnpm style-check

unit-test:
  stage: test
  script:
    - apt update && apt install -y curl
    - pnpm install
    - SECRET_KEY=$SECRET_KEY pnpm test

deploy:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
