apiVersion: v1
kind: Namespace
metadata:
  name: suprachat
---
apiVersion: v1
kind: Service
metadata:
  name: suprachat-backend
  namespace: suprachat
spec:
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  ports:
    - name: web
      port: 80
      targetPort: web
  selector:
    app: suprachat-backend
  externalTrafficPolicy: Local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: suprachat-backend
  namespace: suprachat
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: suprachat-backend
  template:
    metadata:
      labels:
        app: suprachat-backend
    spec:
      containers:
        - name: suprachat-backend
          image: ttl.sh/suprachat-backend-24af2935-f192-4abd-b38f-e642b17853ac@sha256:c55902b406d09b7bd77319c53aff8ca35607fc9b6a9efbc1c8427702f34cfa03
          ports:
            - name: web
              containerPort: 3001
          envFrom:
            - configMapRef:
                name: sc-backend-env
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-backend
                  key: SECRET_KEY
            - name: WEBIRC_PASS
              valueFrom:
                secretKeyRef:
                  name: sc-backend
                  key: WEBIRC_PASS
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-backend
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-backend
                  key: S3_SECRET_KEY
            - name: VERCEL_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sc-backend
                  key: VERCEL_ACCESS_TOKEN
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: suprachat-backend
  namespace: suprachat
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: suprachat-suprachat-backend-cors@kubernetescrd
spec:
  tls:
    - hosts:
      - api.suprachat.net
      secretName: sc-backend-cert
  rules:
    - host: api.suprachat.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: suprachat-backend
                port:
                  name: web
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: suprachat
spec:
  acme:
    email: ivan.97galarz@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - http01:
          ingress:
            class: traefik
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  namespace: suprachat
  name: suprachat-backend-cors
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "POST"
      - "OPTIONS"
      - "PUT"
      - "PATCH"
    accessControlAllowOriginList:
      - "https://chat.suprachat.net"
      - "https://suprachat.net"
      - "https://*.suprachat.net"
    accessControlMaxAge: 100
    addVaryHeader: true
    accessControlAllowHeaders:
      - "Authorization"
      - "Content-Type"
