apiVersion: v1
kind: Service
metadata:
  name: ergo-internal
  labels:
    app: ergo
spec:
  type: ClusterIP
  ipFamilyPolicy: RequireDualStack
  ipFamilies: ["IPv6", "IPv4"]
  ports:
    - name: plain
      port: 6667
      targetPort: plain
  selector:
    app: ergo
---
apiVersion: v1
kind: Service
metadata:
  name: ergo-external
  labels:
    app: ergo
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ipFamilyPolicy: RequireDualStack
  ipFamilies: ["IPv6", "IPv4"]
  ports:
    - name: secure
      port: 6697
      targetPort: secure
      nodePort: 6697
    - name: websocket
      port: 6699
      targetPort: websocket
      nodePort: 6699
  selector:
    app: ergo
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  namespace: suprachat
  name: ssl-header
spec:
  headers:
    customRequestHeaders:
      Connection: keep-alive, Upgrade
      Upgrade: websocket
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  namespace: suprachat
  name: ergo-cors
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "POST"
      - "OPTIONS"
      - "PUT"
      - "PATCH"
    accessControlAllowOriginList:
      - "https://suprachat.net"
      - "https://chat.suprachat.net"
      - "https://*.suprachat.net"
    accessControlMaxAge: 100
    addVaryHeader: true
    accessControlAllowHeaders:
      - "Accept"
      - "Authorization"
      - "Content-Type"
      - "Connection"
      - "Upgrade"
      - "X-Forwarded-Proto"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ergo
  namespace: suprachat
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: suprachat-ssl-header@kubernetescrd,suprachat-ergo-cors@kubernetescrd,suprachat-ergo-cors@kubernetescrd
spec:
  tls:
    - hosts:
      - irc.suprachat.net
      secretName: ergo-cert
  rules:
    - host: irc.suprachat.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ergo
                port:
                  name: websocket
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ergo
  namespace: suprachat
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ergo
  template:
    metadata:
      labels:
        app: ergo
    spec:
      shareProcessNamespace: true
      containers:
        - name: ergo
          image: ttl.sh/suprachat-ergo-95d805f6-73f6-4105-93b4-f1b950b17051:10m@sha256:d7cc3005b62921fe8cb9f6c688659c19feedf42af236b868c40605ae99006753
          ports:
            - containerPort: 6667
              name: plain
            - containerPort: 6697
              name: secure
            - containerPort: 443
              name: websocket
          readinessProbe:
            tcpSocket:
              port: 6697
          livenessProbe:
            periodSeconds: 60
            tcpSocket:
              port: 6697
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: sc-backend-env
                  key: MONGO_URI
            - name: AUTH_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: sc-backend-env
                  key: ERGO_AUTH_LOG_LEVEL
          volumeMounts:
            - name: ergo-storage
              mountPath: /ircd/db/
            - name: ergo-cert
              mountPath: /ircd/tls/
              readOnly: true
            - name: ergo-config
              mountPath: /ircd/
            - name: dkim
              mountPath: /ircd/dkim/
              readOnly: true
            - name: lang
              mountPath: /ircd/lang/
              readOnly: true
      volumes:
        - name: ergo-config
          configMap:
            name: ergo-config
        - name: ergo-storage
          persistentVolumeClaim:
            claimName: ergo-storage
        - name: ergo-cert
          secret:
            secretName: ergo-cert
        - name: dkim
          secret:
            secretName: ergo-dkim
        - name: lang
          configMap:
            name: ergo-lang
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ergo-storage
  namespace: suprachat
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: suprachat
  name: irc.suprachat.net
spec:
  secretName: ergo-cert
  dnsNames:
  - irc.suprachat.net
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
